apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-app
  ports:
    - name: proxy
      protocol: TCP
      port: 3000
      targetPort: 3000